### PR TITLE
Updated travis.yml and pom.xml

### PR DESCRIPTION
**Pull request by AdriaanDeVos**
Updated travis.yml and pom.xml according to https://octopull.rmhartog.me/
<configuration

### CODE REVIEW

**Comment by AdriaanDeVos** [comment]
Can someone explain why github is showing that one build failed?
Travis shows that they both passed
https://travis-ci.org/tcbaars/TI2206_Group0/builds/82172507
<bug

**Comment by tcbaars** [comment]
I can not see anything wrong with it. It looks identical to that on https://octopull.rmhartog.me/. Maybe put echo  "$TRAVIS_PULL_REQUEST" before - '[ "$BUILD_PR_BRANCH" = "true" ] && { [ "$TRAVIS_PULL_REQUEST" != "false" ] || exit 1; } && echo "OCTOPULL_SHA=$(git rev-parse HEAD)"; true'
So we can see if it is false or not.
Maybe it is a problem with whitespacing.

**Comment by tcbaars** [comment]
It turns out that $TRAVIS_PULL_REQUEST was false so i shall email Reinier Hartog, but for now i set the exit status to 0. < bug

**Comment by AdriaanDeVos** [comment]
Good Catch! Merging now because you solved the problem.
<review

**Pull request merged**
