### PR TITLE
Entityspawnertest

### PR DESCRIPTION
**Pull request by DylanStraub**
< testing

### CODE REVIEW

**Comment by tcbaars** [comment]
Getting there, maybe one test you could add for the EnemySpawnerTest is keep updating until the current number of enemies is no longer zero. Then when it is in the final stage, keep updating until it is no longer active. < review

**Comment by DylanStraub** [comment]
how much do you need to update for it to be inactive? can that even be tested (is it always inactive when updating so many times). < review

**Comment by tcbaars** [comment]
@DylanStraub I mean when there is at least one entity spawned it is active, and entities will no longer be spawned when it has been set to final stage. So you have to just keep updating until the enemies have gone off-screen and despawned. And once the current number of enemies is zero, it becomes inactive.

**Comment by tcbaars** [comment]
Looks better, maybe you can remove the "assertFalse(enemyspawner.getNumberEnemies() == 0);" because otherwise the while loop wouldn't be exited. < review

**Pull request merged**
